// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8B2pUliGXTokhyBHbccTUwlKYMTPEvpM',
    appId: '1:1070643236738:web:386e77cf1efa8b6396899b',
    messagingSenderId: '1070643236738',
    projectId: 'coffee-shop-f8b84',
    authDomain: 'coffee-shop-f8b84.firebaseapp.com',
    storageBucket: 'coffee-shop-f8b84.firebasestorage.app',
    measurementId: 'G-B0SNW7VEMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hncVxAj3RxzZoHYlL6evsPExgX2bg8M',
    appId: '1:1070643236738:android:9a514658432142f496899b',
    messagingSenderId: '1070643236738',
    projectId: 'coffee-shop-f8b84',
    storageBucket: 'coffee-shop-f8b84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGvs8E_WWtyo2tAo-3XP0_wAclf_u56o',
    appId: '1:1070643236738:ios:fdf8d20b26fa05b896899b',
    messagingSenderId: '1070643236738',
    projectId: 'coffee-shop-f8b84',
    storageBucket: 'coffee-shop-f8b84.firebasestorage.app',
    iosBundleId: 'com.example.sandwichShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtGvs8E_WWtyo2tAo-3XP0_wAclf_u56o',
    appId: '1:1070643236738:ios:fdf8d20b26fa05b896899b',
    messagingSenderId: '1070643236738',
    projectId: 'coffee-shop-f8b84',
    storageBucket: 'coffee-shop-f8b84.firebasestorage.app',
    iosBundleId: 'com.example.sandwichShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8B2pUliGXTokhyBHbccTUwlKYMTPEvpM',
    appId: '1:1070643236738:web:9558302b615cab6396899b',
    messagingSenderId: '1070643236738',
    projectId: 'coffee-shop-f8b84',
    authDomain: 'coffee-shop-f8b84.firebaseapp.com',
    storageBucket: 'coffee-shop-f8b84.firebasestorage.app',
    measurementId: 'G-0Y382PBQP8',
  );
}
